### ISSUE TITLE
License needs more clarification

### ISSUE THREAD

**Issue by top-master** [stefan-zobel/minifuture#1]
Your readme's license-section currently (at time of writting) only mentions:
>"GNU General Public License, version 2, [with the Classpath Exception](https://github.com/stefan-zobel/minifuture/blob/master/GPL_ClasspathException) (and [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) for JSR-166 derived code)"

### It would be great to include a more detailed clarification, like:

* This library's latest-version includes 18 `*.java` files.
* 9 of said files are under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) licnese
    >Where said license allows you to use almost any sub-license you want.
* 9 other of said files are under [`Classpath exception`](https://github.com/stefan-zobel/minifuture/blob/master/GPL_ClasspathException).

Where said "Classpath" license-exception allows your executables:
* "`to link this library`" (no matter if statically or dynamically),
* "`and to copy and distribute the resulting executable under terms of your
    choice`",
* But those who re-distribute this library's source-code form, not "executable" binary, can only do that under the terms of GPL 2.0.
    >In other words, our source-codes always remain GPL 2.0, but your executable can link to them statically and/or dynamically, which is even more permissive than LGPL and/or GPL.

## Background
It toke a lot of time to explain my co-workers and boss that using this library does not force us to open-source our project.

Adding above said details to the README should speed things up.

**Comment by top-master** [comment]
Sorry, just noticed https://github.com/streamsupport/streamsupport

Seems I need to create an issue there, not here, thanks for your time.

**Comment by stefan-zobel** [comment]
I get your point (it is always a PITA to explain to people what "GPLv2 + Classpath Exception" means).
I took the liberty to treat the license section in your fork as a PR and merged that.
